// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  GET_DETAIL,
  PATCH_UPDATE,
  DELETE_SURVEY,
} from "@/lib/server/handlers";

export const GET = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => GET_DETAIL(request, ctx));

export const PATCH = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => PATCH_UPDATE(request, ctx));

export const DELETE = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => DELETE_SURVEY(request, ctx));
