// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  GET_APP_SETTINGS,
  PATCH_APP_SETTINGS,
} from "@/lib/server/handlers";

export const GET = route(async (request: import("next/server").NextRequest) => GET_APP_SETTINGS());

export const PATCH = route(async (request: import("next/server").NextRequest) => PATCH_APP_SETTINGS(request));
