// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  GET_TRANSLATIONS,
  POST_TRANSLATIONS,
} from "@/lib/server/handlers";

export const GET = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => GET_TRANSLATIONS(request, ctx));

export const POST = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => POST_TRANSLATIONS(request, ctx));
