// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  POST_FOLLOW_UP,
} from "@/lib/server/handlers";

export const POST = route(async (request: import("next/server").NextRequest) => POST_FOLLOW_UP(request));
