// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  GET_RESPONDENT,
  PATCH_RESPONDENT,
  DELETE_RESPONDENT,
} from "@/lib/server/handlers";

export const GET = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => GET_RESPONDENT(request, ctx));

export const PATCH = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => PATCH_RESPONDENT(request, ctx));

export const DELETE = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => DELETE_RESPONDENT(request, ctx));
