/**
 * Server-side report exporters.
 *
 * Turns a persisted `ReportContent` payload into a downloadable file. Every exporter is
 * dependency-light and runs inside the Next.js node runtime:
 *   - PDF   → jsPDF (text layout with page breaks)
 *   - Word  → docx   (.docx)
 *   - Excel → exceljs (.xlsx, several sheets)
 *   - CSV / JSON → plain text
 */
import { jsPDF } from "jspdf";
import { Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import ExcelJS from "exceljs";
import type { ReportContent } from "@/lib/types-analytics";

export type ReportFormat = "pdf" | "word" | "excel" | "csv" | "json";

export const REPORT_FORMATS: ReportFormat[] = ["pdf", "word", "excel", "csv", "json"];

export function isReportFormat(value: string): value is ReportFormat {
  return (REPORT_FORMATS as string[]).includes(value);
}

export const REPORT_MIME: Record<ReportFormat, string> = {
  pdf: "application/pdf",
  word: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  excel: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  csv: "text/csv; charset=utf-8",
  json: "application/json; charset=utf-8",
};

export const REPORT_EXTENSION: Record<ReportFormat, string> = {
  pdf: "pdf",
  word: "docx",
  excel: "xlsx",
  csv: "csv",
  json: "json",
};

function formatWhen(iso: string) {
  try {
    return new Date(iso).toLocaleString("en-PH", { dateStyle: "medium", timeStyle: "short" });
  } catch {
    return iso;
  }
}

function safeName(value: string) {
  return (
    (value || "report")
      .replace(/[^a-z0-9._-]+/gi, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 80) || "report"
  );
}

export function reportFileName(content: ReportContent, format: ReportFormat) {
  const reportId = content.reportId ? `-${content.reportId.slice(0, 8)}` : "";
  return `${safeName(`${content.reportType}-report-${content.survey.title}`)}${reportId}.${REPORT_EXTENSION[format]}`;
}

/** Flat key/value overview lines reused by every exporter. */
function overviewLines(content: ReportContent) {
  const o = content.overview;
  return [
    { label: "Survey", value: content.survey.title },
    { label: "Topic", value: content.survey.topic },
    { label: "Stakeholder", value: content.survey.stakeholder },
    { label: "Interview method", value: content.survey.interviewMethod },
    { label: "Interview mode", value: content.survey.interviewMode },
    { label: "Language", value: content.survey.language },
    { label: "Survey version", value: `v${content.survey.version} (${content.survey.status})` },
    { label: "Total responses", value: String(o.totalResponses) },
    { label: "Completed interviews", value: String(o.completedInterviews) },
    { label: "Completion rate", value: `${o.completionRate}%` },
    { label: "Average Likert score", value: String(o.averageLikertScore) },
    { label: "Satisfaction", value: `${o.averageSatisfactionPercent}%` },
    { label: "Respondents", value: String(o.totalRespondents) },
    { label: "Average duration", value: `${o.averageDurationSec}s` },
    { label: "Offline pending sync", value: String(o.offlinePending) },
    { label: "Generated at", value: formatWhen(content.generatedAt) },
    { label: "Generated by", value: content.generatedBy },
    { label: "AI engine", value: content.aiProvider },
  ];
}


/* -------------------------------------------------------------------------- */
/* CSV / JSON                                                                  */
/* -------------------------------------------------------------------------- */

function csvCell(value: unknown) {
  const text = value === null || value === undefined ? "" : String(value);
  return `"${text.replace(/"/g, '""').replace(/\r?\n/g, " ")}"`;
}

export function buildReportCsv(content: ReportContent): string {
  const rows: string[] = [];
  rows.push(csvCell(`${content.reportType} REPORT — ${content.survey.title}`));
  rows.push("");
  rows.push([csvCell("Field"), csvCell("Value")].join(","));
  for (const line of overviewLines(content)) rows.push([csvCell(line.label), csvCell(line.value)].join(","));

  rows.push("");
  rows.push(csvCell("Sentiment distribution"));
  rows.push([csvCell("Label"), csvCell("Count"), csvCell("Percentage")].join(","));
  for (const entry of content.sentiment) rows.push([csvCell(entry.label), csvCell(entry.value), csvCell(`${entry.percentage}%`)].join(","));

  rows.push("");
  rows.push(csvCell("Response trend"));
  rows.push([csvCell("Date"), csvCell("Responses"), csvCell("Completed")].join(","));
  for (const point of content.trend) rows.push([csvCell(point.date), csvCell(point.responses), csvCell(point.completed)].join(","));

  rows.push("");
  rows.push(csvCell("Question analytics"));
  rows.push(
    [
      csvCell("Code"),
      csvCell("Question"),
      csvCell("Type"),
      csvCell("Category"),
      csvCell("Answered"),
      csvCell("Answer rate %"),
      csvCell("Likert average"),
      csvCell("Interpretation"),
    ].join(","),
  );
  for (const question of content.questions) {
    rows.push(
      [
        csvCell(question.code),
        csvCell(question.text),
        csvCell(question.type),
        csvCell(question.category ?? ""),
        csvCell(question.answered),
        csvCell(question.answerRate),
        csvCell(question.likertAverage ?? ""),
        csvCell(question.likertInterpretation ?? ""),
      ].join(","),
    );
  }

  if (content.rawResponses.length) {
    rows.push("");
    rows.push(csvCell(content.reportType === "SUMMARY" ? "Sample responses" : "Raw responses"));
    rows.push(
      [
        csvCell("Response"),
        csvCell("Respondent"),
        csvCell("Group"),
        csvCell("Submitted"),
        csvCell("Source"),
        csvCell("Status"),
        csvCell("Question"),
        csvCell("Answer"),
      ].join(","),
    );
    for (const response of content.rawResponses) {
      for (const answer of response.answers) {
        rows.push(
          [
            csvCell(response.responseId.slice(0, 8)),
            csvCell(response.respondent),
            csvCell(response.group ?? ""),
            csvCell(formatWhen(response.submittedAt)),
            csvCell(response.source),
            csvCell(response.status),
            csvCell(`${answer.code} ${answer.question}`),
            csvCell(answer.answer),
          ].join(","),
        );
      }
    }
  }

  rows.push("");
  rows.push(csvCell("AI summary"));
  rows.push(csvCell(content.aiSummary));
  return rows.join("\r\n");
}

export function buildReportJson(content: ReportContent): string {
  return JSON.stringify(content, null, 2);
}

/* -------------------------------------------------------------------------- */
/* PDF (jsPDF)                                                                 */
/* -------------------------------------------------------------------------- */

export function buildReportPdf(content: ReportContent): Buffer {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 42;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const ensure = (height: number) => {
    if (y + height > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };
  const line = (value: string, size = 10, style: "normal" | "bold" = "normal", indent = 0) => {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(value ?? "", maxWidth - indent) as string[];
    for (const piece of lines) {
      ensure(size + 6);
      doc.text(piece, margin + indent, y);
      y += size + 4;
    }
  };
  const gap = (size = 8) => {
    y += size;
  };
  const heading = (value: string) => {
    ensure(40);
    gap(8);
    doc.setFillColor(59, 107, 246);
    doc.rect(margin, y - 11, 3, 13, "F");
    line(value, 13, "bold", 10);
    gap(2);
  };

  line(content.title, 18, "bold");
  line(`${content.survey.topic} · ${content.survey.stakeholder}`, 10);
  line(
    `Generated ${formatWhen(content.generatedAt)} by ${content.generatedBy} · AI engine: ${content.aiProvider}`,
    9,
  );
  gap(4);
  doc.setDrawColor(220, 226, 240);
  doc.line(margin, y, pageWidth - margin, y);

  heading("Executive summary");
  line(content.aiSummary, 10);

  heading("Key metrics");
  for (const item of overviewLines(content)) line(`${item.label}: ${item.value}`, 10);

  if (content.trend.length) {
    heading("Response trend");
    for (const point of content.trend) line(`${point.date} — responses: ${point.responses}, completed: ${point.completed}`, 9);
  }

  if (content.sentiment.length) {
    heading("Sentiment distribution");
    for (const entry of content.sentiment) line(`${entry.label}: ${entry.value} (${entry.percentage}%)`, 10);
  }

  if (content.demographics.length) {
    heading("Respondent groups");
    for (const entry of content.demographics) line(`${entry.label}: ${entry.value} (${entry.percentage}%)`, 10);
  }

  heading("Question analysis");
  for (const question of content.questions) {
    line(`${question.code}. ${question.text}`, 10, "bold");
    const bits = [
      `Type: ${question.type}`,
      question.category ? `Category: ${question.category}` : "",
      `Answered: ${question.answered} (${question.answerRate}%)`,
      question.likertAverage !== null && question.likertAverage !== undefined ? `Likert average: ${question.likertAverage}` : "",
      question.likertInterpretation ?? "",
      question.numericAverage !== null && question.numericAverage !== undefined ? `Average: ${question.numericAverage}` : "",
    ].filter(Boolean);
    line(bits.join(" · "), 9);
    for (const entry of question.distribution ?? []) line(`${entry.label}: ${entry.value} (${entry.percentage}%)`, 9, "normal", 10);
    for (const sample of question.sampleAnswers ?? []) line(`• ${sample}`, 9, "normal", 10);
    gap(3);
  }

  if (content.keywords.length) {
    heading("Keywords");
    line(content.keywords.map((k) => `${k.keyword} (${k.count})`).join(", "), 10);
  }
  if (content.themes.length) {
    heading("Themes");
    for (const theme of content.themes) line(`• ${theme.theme} — ${theme.count} mentions`, 10);
  }
  if (content.painPoints.length) {
    heading("Pain points");
    for (const item of content.painPoints) line(`• ${item}`, 10);
  }
  if (content.suggestions.length) {
    heading("Suggestions");
    for (const item of content.suggestions) line(`• ${item}`, 10);
  }
  if (content.concerns.length) {
    heading("Concerns");
    for (const item of content.concerns) line(`• ${item}`, 10);
  }

  if (content.rawResponses.length) {
    heading(content.reportType === "SUMMARY" ? "Sample responses" : "Raw responses");
    for (const response of content.rawResponses) {
      line(`${response.respondent}${response.group ? ` (${response.group})` : ""} — ${formatWhen(response.submittedAt)} · ${response.source} · ${response.status}`, 9, "bold");
      for (const answer of response.answers) line(`${answer.code}: ${answer.answer}`, 9, "normal", 10);
      gap(3);
    }
  }

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(`WPU AI Interview & Survey · ${content.survey.title}`, margin, pageHeight - 20);
    doc.text(`Page ${page} of ${pageCount}`, pageWidth - margin, pageHeight - 20, { align: "right" });
    doc.setTextColor(0);
  }

  return Buffer.from(doc.output("arraybuffer"));
}


/* -------------------------------------------------------------------------- */
/* Word (docx)                                                                 */
/* -------------------------------------------------------------------------- */

function docxHeading(value: string) {
  return new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 120 }, children: [new TextRun(value)] });
}

function docxBullet(value: string) {
  return new Paragraph({ bullet: { level: 0 }, spacing: { after: 60 }, children: [new TextRun(value)] });
}

function docxTable(headers: string[], rows: string[][]) {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        tableHeader: true,
        children: headers.map(
          (header) =>
            new TableCell({
              shading: { fill: "EEF2FF" },
              children: [new Paragraph({ children: [new TextRun({ text: header, bold: true, size: 20 })] })],
            }),
        ),
      }),
      ...rows.map(
        (row) =>
          new TableRow({
            children: row.map(
              (cell) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: cell, size: 20 })] })] }),
            ),
          }),
      ),
    ],
  });
}

export async function buildReportDocx(content: ReportContent): Promise<Buffer> {
  const children: (Paragraph | Table)[] = [
    new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun(content.title)] }),
    new Paragraph({ children: [new TextRun({ text: `${content.survey.topic} · ${content.survey.stakeholder}`, size: 22 })] }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated ${formatWhen(content.generatedAt)} by ${content.generatedBy} · AI engine: ${content.aiProvider}`,
          size: 18,
          color: "64748B",
        }),
      ],
    }),
  ];

  children.push(docxHeading("Executive summary"));
  children.push(new Paragraph({ children: [new TextRun(content.aiSummary)] }));

  children.push(docxHeading("Key metrics"));
  children.push(docxTable(["Field", "Value"], overviewLines(content).map((l) => [l.label, l.value])));

  if (content.sentiment.length) {
    children.push(docxHeading("Sentiment distribution"));
    children.push(docxTable(["Label", "Count", "Percentage"], content.sentiment.map((s) => [s.label, String(s.value), `${s.percentage}%`])));
  }

  if (content.trend.length) {
    children.push(docxHeading("Response trend"));
    children.push(docxTable(["Date", "Responses", "Completed"], content.trend.map((t) => [t.date, String(t.responses), String(t.completed)])));
  }

  if (content.demographics.length) {
    children.push(docxHeading("Respondent groups"));
    children.push(docxTable(["Group", "Responses", "Percentage"], content.demographics.map((g) => [g.label, String(g.value), `${g.percentage}%`])));
  }

  children.push(docxHeading("Question analysis"));
  children.push(
    docxTable(
      ["Code", "Question", "Type", "Answered", "Answer rate", "Likert average"],
      content.questions.map((q) => [
        q.code,
        q.text,
        q.type,
        String(q.answered),
        `${q.answerRate}%`,
        q.likertAverage === null || q.likertAverage === undefined ? "—" : String(q.likertAverage),
      ]),
    ),
  );

  const textQuestions = content.questions.filter((q) => (q.sampleAnswers ?? []).length || q.likertInterpretation);
  if (textQuestions.length) {
    children.push(docxHeading("Question detail"));
    for (const question of textQuestions) {
      children.push(new Paragraph({ spacing: { before: 120 }, children: [new TextRun({ text: `${question.code}. ${question.text}`, bold: true })] }));
      if (question.likertInterpretation) children.push(docxBullet(`Interpretation: ${question.likertInterpretation}`));
      for (const entry of question.distribution ?? []) children.push(docxBullet(`${entry.label}: ${entry.value} (${entry.percentage}%)`));
      for (const sample of question.sampleAnswers ?? []) children.push(docxBullet(`“${sample}”`));
    }
  }

  if (content.keywords.length) {
    children.push(docxHeading("Keywords"));
    children.push(new Paragraph({ children: [new TextRun(content.keywords.map((k) => `${k.keyword} (${k.count})`).join(", "))] }));
  }
  if (content.themes.length) {
    children.push(docxHeading("Themes"));
    for (const theme of content.themes) children.push(docxBullet(`${theme.theme} — ${theme.count} mentions`));
  }
  for (const [title, items] of [
    ["Pain points", content.painPoints],
    ["Suggestions", content.suggestions],
    ["Concerns", content.concerns],
  ] as [string, string[]][]) {
    if (!items.length) continue;
    children.push(docxHeading(title));
    for (const item of items) children.push(docxBullet(item));
  }

  if (content.rawResponses.length) {
    children.push(docxHeading(content.reportType === "SUMMARY" ? "Sample responses" : "Raw responses"));
    children.push(
      docxTable(
        ["Respondent", "Group", "Submitted", "Source", "Question", "Answer"],
        content.rawResponses.flatMap((response) =>
          response.answers.map((answer) => [
            response.respondent,
            response.group ?? "—",
            formatWhen(response.submittedAt),
            response.source,
            `${answer.code} ${answer.question}`,
            answer.answer,
          ]),
        ),
      ),
    );
  }

  const document = new Document({ sections: [{ children }] });
  return Packer.toBuffer(document);
}

/* -------------------------------------------------------------------------- */
/* Excel (exceljs)                                                             */
/* -------------------------------------------------------------------------- */

function styleHeader(row: ExcelJS.Row) {
  row.font = { bold: true, color: { argb: "FF1E3A8A" } };
  row.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE0E7FF" } };
    cell.border = { bottom: { style: "thin", color: { argb: "FF94A3B8" } } };
  });
}

export async function buildReportExcel(content: ReportContent): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "WPU AI Interview & Survey System";
  workbook.created = new Date(content.generatedAt);

  const overview = workbook.addWorksheet("Overview");
  overview.columns = [
    { header: "Field", key: "label", width: 30 },
    { header: "Value", key: "value", width: 60 },
  ];
  styleHeader(overview.getRow(1));
  overview.addRow({ label: "Report", value: content.title });
  for (const item of overviewLines(content)) overview.addRow({ label: item.label, value: item.value });
  overview.addRow({ label: "AI summary", value: content.aiSummary });

  const questions = workbook.addWorksheet("Questions");
  questions.columns = [
    { header: "Code", key: "code", width: 10 },
    { header: "Question", key: "text", width: 60 },
    { header: "Type", key: "type", width: 16 },
    { header: "Category", key: "category", width: 22 },
    { header: "Answered", key: "answered", width: 12 },
    { header: "Answer rate %", key: "answerRate", width: 14 },
    { header: "Likert average", key: "likert", width: 14 },
    { header: "Interpretation", key: "interpretation", width: 30 },
    { header: "Numeric average", key: "numeric", width: 16 },
  ];
  styleHeader(questions.getRow(1));
  for (const question of content.questions) {
    questions.addRow({
      code: question.code,
      text: question.text,
      type: question.type,
      category: question.category ?? "",
      answered: question.answered,
      answerRate: question.answerRate,
      likert: question.likertAverage ?? "",
      interpretation: question.likertInterpretation ?? "",
      numeric: question.numericAverage ?? "",
    });
  }

  const distributions = workbook.addWorksheet("Distributions");
  distributions.columns = [
    { header: "Question", key: "question", width: 50 },
    { header: "Option", key: "option", width: 28 },
    { header: "Count", key: "count", width: 10 },
    { header: "Percentage", key: "percentage", width: 12 },
  ];
  styleHeader(distributions.getRow(1));
  for (const question of content.questions) {
    for (const entry of question.distribution ?? []) {
      distributions.addRow({ question: `${question.code} ${question.text}`, option: entry.label, count: entry.value, percentage: entry.percentage });
    }
  }

  const sentiment = workbook.addWorksheet("Sentiment & Trend");
  sentiment.columns = [
    { header: "Sentiment", key: "label", width: 18 },
    { header: "Count", key: "count", width: 10 },
    { header: "Percentage", key: "percentage", width: 12 },
  ];
  styleHeader(sentiment.getRow(1));
  for (const entry of content.sentiment) sentiment.addRow({ label: entry.label, count: entry.value, percentage: entry.percentage });
  sentiment.addRow({});
  const trendHeader = sentiment.addRow(["Trend date", "Responses", "Completed"]);
  styleHeader(trendHeader);
  for (const point of content.trend) sentiment.addRow([point.date, point.responses, point.completed]);

  if (content.rawResponses.length) {
    const responses = workbook.addWorksheet("Responses");
    responses.columns = [
      { header: "Respondent", key: "respondent", width: 26 },
      { header: "Group", key: "group", width: 20 },
      { header: "Submitted", key: "submitted", width: 22 },
      { header: "Source", key: "source", width: 16 },
      { header: "Status", key: "status", width: 14 },
      { header: "Question", key: "question", width: 50 },
      { header: "Answer", key: "answer", width: 60 },
    ];
    styleHeader(responses.getRow(1));
    for (const response of content.rawResponses) {
      for (const answer of response.answers) {
        responses.addRow({
          respondent: response.respondent,
          group: response.group ?? "",
          submitted: formatWhen(response.submittedAt),
          source: response.source,
          status: response.status,
          question: `${answer.code} ${answer.question}`,
          answer: answer.answer,
        });
      }
    }
  }

  const insights = workbook.addWorksheet("AI Insights");
  insights.columns = [
    { header: "Type", key: "type", width: 20 },
    { header: "Value", key: "value", width: 90 },
  ];
  styleHeader(insights.getRow(1));
  insights.addRow({ type: "Summary", value: content.aiSummary });
  for (const keyword of content.keywords) insights.addRow({ type: "Keyword", value: `${keyword.keyword} (${keyword.count})` });
  for (const theme of content.themes) insights.addRow({ type: "Theme", value: `${theme.theme} (${theme.count})` });
  for (const item of content.painPoints) insights.addRow({ type: "Pain point", value: item });
  for (const item of content.suggestions) insights.addRow({ type: "Suggestion", value: item });
  for (const item of content.concerns) insights.addRow({ type: "Concern", value: item });

  const written = await workbook.xlsx.writeBuffer();
  return Buffer.from(written as ArrayBuffer);
}

/* -------------------------------------------------------------------------- */
/* Shared entry point                                                          */
/* -------------------------------------------------------------------------- */

/** Builds the requested export, returning the binary payload and its file name. */
export async function buildReportFile(
  content: ReportContent,
  format: ReportFormat,
): Promise<{ body: Buffer; fileName: string; contentType: string }> {
  let body: Buffer;
  switch (format) {
    case "pdf":
      body = buildReportPdf(content);
      break;
    case "word":
      body = await buildReportDocx(content);
      break;
    case "excel":
      body = await buildReportExcel(content);
      break;
    case "json":
      body = Buffer.from(buildReportJson(content), "utf8");
      break;
    case "csv":
    default:
      body = Buffer.from(buildReportCsv(content), "utf8");
      break;
  }
  return { body, fileName: reportFileName(content, format), contentType: REPORT_MIME[format] };
}


