// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  GET_RESPONDENTS,
  POST_RESPONDENT,
} from "@/lib/server/handlers";

export const GET = route(async (request: import("next/server").NextRequest) => GET_RESPONDENTS(request));

export const POST = route(async (request: import("next/server").NextRequest) => POST_RESPONDENT(request));
