// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  PATCH_BANK,
  DELETE_BANK,
} from "@/lib/server/handlers";

export const PATCH = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => PATCH_BANK(request, ctx));

export const DELETE = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => DELETE_BANK(request, ctx));
