// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  GET_PUBLIC_TRANSLATIONS,
  POST_PUBLIC_TRANSLATE,
} from "@/lib/server/handlers";

export const GET = route(async (request: import("next/server").NextRequest) => GET_PUBLIC_TRANSLATIONS(request));

export const POST = route(async (request: import("next/server").NextRequest) => POST_PUBLIC_TRANSLATE(request));
