// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  GET_REPORTS,
  POST_REPORT,
} from "@/lib/server/handlers";

export const GET = route(async (request: import("next/server").NextRequest) => GET_REPORTS(request));

export const POST = route(async (request: import("next/server").NextRequest) => POST_REPORT(request));
