// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  DELETE_SURVEY_PERMANENT,
} from "@/lib/server/handlers";

export const DELETE = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => DELETE_SURVEY_PERMANENT(request, ctx));