// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  GET_SURVEY,
} from "@/lib/server/handlers";

export const GET = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => GET_SURVEY(request, ctx));
