// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  POST_BULK_GENERATE,
} from "@/lib/server/handlers";

export const POST = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => POST_BULK_GENERATE(request, ctx));
