// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  GET_LIST,
  POST_CREATE,
} from "@/lib/server/handlers";

export const GET = route(async (request: import("next/server").NextRequest) => GET_LIST(request));

export const POST = route(async (request: import("next/server").NextRequest) => POST_CREATE(request));
