/**
 * Generates the thin Next.js route adapters that delegate to the central
 * handler registry (src/lib/server/handlers.ts).
 * Usage: node scripts/gen-routes.mjs
 */
import { mkdirSync, writeFileSync, rmSync } from "node:fs";

// [routePath, { method: handlerName }, hasDynamicParams]
const ROUTES = [
  ["api/admin/dashboard", { GET: "GET" }, false],
  ["api/admin/surveys", { GET: "GET_LIST", POST: "POST_CREATE" }, false],
  ["api/admin/surveys/[id]", { GET: "GET_DETAIL", PATCH: "PATCH_UPDATE", DELETE: "DELETE_SURVEY" }, true],
  ["api/admin/surveys/[id]/publish", { POST: "POST_PUBLISH" }, true],
  ["api/admin/surveys/[id]/status", { POST: "POST_STATUS" }, true],
  ["api/admin/surveys/[id]/duplicate", { POST: "POST_DUPLICATE" }, true],
  ["api/admin/surveys/[id]/questions", { GET: "GET_QUESTIONS", POST: "POST_QUESTION" }, true],
  ["api/admin/surveys/[id]/questions/reorder", { PUT: "PUT_REORDER" }, true],
  ["api/admin/surveys/[id]/questions/generate", { POST: "POST_BULK_GENERATE" }, true],
  ["api/admin/surveys/[id]/questions/regenerate", { POST: "POST_REGENERATE" }, true],
  ["api/admin/surveys/[id]/questions/[questionId]", { PATCH: "PATCH_QUESTION", DELETE: "DELETE_QUESTION" }, true],
  ["api/admin/surveys/[id]/questions/[questionId]/duplicate", { POST: "POST_DUPLICATE_QUESTION" }, true],
  ["api/admin/surveys/[id]/translations", { GET: "GET_TRANSLATIONS", POST: "POST_TRANSLATIONS" }, true],
  ["api/admin/bank", { GET: "GET_BANK", POST: "POST_BANK" }, false],
  ["api/admin/bank/import", { POST: "POST_BANK_IMPORT" }, false],
  ["api/admin/bank/[bankId]", { PATCH: "PATCH_BANK", DELETE: "DELETE_BANK" }, true],
  ["api/admin/bank/tags", { GET: "GET_TAGS", POST: "POST_TAG" }, false],
  ["api/admin/respondents", { GET: "GET_RESPONDENTS", POST: "POST_RESPONDENT" }, false],
  ["api/admin/respondents/[respondentId]", { GET: "GET_RESPONDENT", PATCH: "PATCH_RESPONDENT", DELETE: "DELETE_RESPONDENT" }, true],
  ["api/admin/responses", { GET: "GET_RESPONSES" }, false],
  ["api/admin/responses/[responseId]", { GET: "GET_RESPONSE" }, true],
  ["api/admin/sessions", { GET: "GET_SESSIONS" }, false],
  ["api/admin/qr", { GET: "GET_QR", POST: "POST_QR" }, false],
  ["api/admin/qr/[qrId]", { GET: "GET_QR_DETAIL", PATCH: "PATCH_QR", DELETE: "DELETE_QR" }, true],
  ["api/admin/analytics", { GET: "GET_ANALYTICS" }, false],
  ["api/admin/analytics/unstructured", { GET: "GET_UNSTRUCTURED" }, false],
  ["api/admin/analytics/facets", { GET: "GET_FACETS" }, false],
  ["api/admin/reports", { GET: "GET_REPORTS", POST: "POST_REPORT" }, false],
  ["api/admin/reports/[reportId]", { GET: "GET_REPORT", DELETE: "DELETE_REPORT" }, true],
  ["api/admin/reports/[reportId]/regenerate", { POST: "POST_REGENERATE_REPORT" }, true],
  ["api/admin/reports/[reportId]/download", { GET: "GET_REPORT_DOWNLOAD" }, true],
  ["api/admin/sync", { GET: "GET_SYNC" }, false],
  ["api/admin/sync/[syncId]/resolve", { POST: "POST_RESOLVE" }, true],
  ["api/admin/audit", { GET: "GET_AUDIT" }, false],
  ["api/admin/settings", { GET: "GET_APP_SETTINGS", PATCH: "PATCH_APP_SETTINGS" }, false],
  ["api/public/survey/[token]", { GET: "GET_SURVEY" }, true],
  ["api/public/submit", { POST: "POST_SUBMIT" }, false],
  ["api/public/sync", { POST: "POST_SYNC" }, false],
  ["api/public/follow-up", { POST: "POST_FOLLOW_UP" }, false],
  ["api/public/translate", { GET: "GET_PUBLIC_TRANSLATIONS", POST: "POST_PUBLIC_TRANSLATE" }, false],
];

/** Handlers that take no arguments. */
const ZERO_ARG = new Set(["GET_TAGS", "GET_APP_SETTINGS", "GET", "GET_FACETS"]);

let count = 0;
for (const [routePath, methods, dynamic] of ROUTES) {
  const dir = `src/app/${routePath}`;
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });

  const imports = Object.entries(methods).map(([method, handler]) => {
    if (handler === method) return `  ${handler} as ${handler}_H,`;
    return `  ${handler},`;
  });

  const lines = [
    "// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.",
    'import { route } from "@/lib/server/api";',
    "import {",
    ...imports,
    '} from "@/lib/server/handlers";',
    "",
  ];

  for (const [method, handler] of Object.entries(methods)) {
    const alias = handler === method ? `${handler}_H` : handler;
    const call = ZERO_ARG.has(handler) ? `${alias}()` : `${alias}(request${dynamic ? ", ctx" : ""})`;
    const signature = dynamic
      ? `(request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> })`
      : `(request: import("next/server").NextRequest)`;
    lines.push(`export const ${method} = route(async ${signature} => ${call});`, "");
  }

  writeFileSync(`${dir}/route.ts`, lines.join("\n"), "utf8");
  count += 1;
}

console.log(`[gen-routes] wrote ${count} route files`);