/**
 * Runs before `next start` (npm `prestart` hook).
 *
 * IMPORTANT: the database bootstrap (prisma db push + admin seed) must never sit
 * between the start command and the moment the HTTP server binds its port. Render
 * scans for an open port as soon as the start command runs and logs
 * "==> No open ports detected, continuing to scan..." until it finds one, so a slow
 * bootstrap delays the deploy and makes cold starts on the free tier flaky.
 *
 * Modes via DB_ENSURE_ON_START:
 *   background (default) — start `next start` right away, bootstrap Postgres in parallel
 *   block                — legacy behaviour: finish the bootstrap before Next starts
 *   off                  — skip entirely (use when the build already ran `npm run db:ensure-pg`)
 *
 * Local SQLite development is always untouched (DATABASE_URL=file:... skips this).
 */
import { spawn, spawnSync } from "node:child_process";

const url = process.env.DATABASE_URL ?? "";
if (!url.startsWith("postgres")) {
  console.log(
    url
      ? "[prestart] local sqlite detected — skipping postgres ensure."
      : "[prestart] DATABASE_URL is not set in this process (npm scripts do not load .env) — skipping postgres ensure.",
  );
  process.exit(0);
}

const mode = (process.env.DB_ENSURE_ON_START ?? "background").trim().toLowerCase();
if (mode === "off" || mode === "false" || mode === "0") {
  console.log("[prestart] DB_ENSURE_ON_START=off — skipping postgres ensure (the build handles it).");
  process.exit(0);
}

// The Prisma client was already generated by `postinstall`/`build`, so the runtime
// bootstrap only has to push the schema and seed. Skip the slow (npx-based) generate
// unless it is explicitly requested.
const env = {
  ...process.env,
  DB_ENSURE_SKIP_GENERATE: process.env.DB_ENSURE_SKIP_GENERATE ?? "1",
};
const args = ["scripts/db-ensure-pg.mjs"];

if (mode === "block") {
  console.log("[prestart] DB_ENSURE_ON_START=block — ensuring postgres schema + seed before start...");
  const r = spawnSync(process.execPath, args, { stdio: "inherit", env });
  if ((r.status ?? 1) !== 0) {
    console.error("[prestart] db ensure failed — starting anyway (login may fail until tables exist).");
  }
  process.exit(0);
}

console.log(
  "[prestart] ensuring postgres schema + seed in the background — `next start` binds its port immediately.",
);
const child = spawn(process.execPath, args, { stdio: "inherit", env, detached: true });
child.on("error", (error) => {
  console.error("[prestart] could not start db ensure:", error.message);
});
child.unref();
process.exit(0);
