// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  PUT_REORDER,
} from "@/lib/server/handlers";

export const PUT = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => PUT_REORDER(request, ctx));
