// AUTO-GENERATED by scripts/gen-routes.mjs — thin adapter to the central handler registry.
import { route } from "@/lib/server/api";
import {
  GET_REPORT,
  DELETE_REPORT,
} from "@/lib/server/handlers";

export const GET = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => GET_REPORT(request, ctx));

export const DELETE = route(async (request: import("next/server").NextRequest, ctx: { params: Promise<Record<string, string>> }) => DELETE_REPORT(request, ctx));
